
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://vatocrtcaogewqdtgjrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdG9jcnRjYW9nZXdxZHRnanJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDY1MzIsImV4cCI6MjA2MDI4MjUzMn0.aOwJLnzqEVn9QtD2uypsmJHLtcJKdRthF-UMvXmw6ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
